import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse1939 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.setOperation(null);
}
}